- name: Get AKS credentials
  command: az aks get-credentials --resource-group rg-cjmenez-cp2 --name aks-cjmenez-cp2 --overwrite-existing

- name: Create namespace
  k8s:
    definition:
      kind: Namespace
      apiVersion: v1
      metadata:
        name: "{{ app_namespace }}"

- name: Deploy Redis
  k8s:
    namespace: "{{ app_namespace }}"
    definition:
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: redis
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: redis
          template:
            metadata:
              labels:
                app: redis
            spec:
              containers:
                - name: redis
                  image: redis:latest
                  ports:
                    - containerPort: 6379
      - apiVersion: v1
        kind: Service
        metadata:
          name: redis
        spec:
          selector:
            app: redis
          ports:
            - port: 6379
              targetPort: 6379

- name: Deploy azure-vote-front
  k8s:
    namespace: "{{ app_namespace }}"
    definition:
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: azure-vote-front
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: azure-vote-front
          template:
            metadata:
              labels:
                app: azure-vote-front
            spec:
              containers:
                - name: azure-vote-front
                  image: "{{ acr_name }}.azurecr.io/azure-vote-front:v1"
                  ports:
                    - containerPort: 80
                  env:
                    - name: REDIS
                      value: redis
      - apiVersion: v1
        kind: Service
        metadata:
          name: azure-vote-front
        spec:
          type: LoadBalancer
          selector:
            app: azure-vote-front
          ports:
            - port: 80
              targetPort: 80
